// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNDuPlEGh1EMomSokJbz4n25IUfMAjfWk',
    appId: '1:889846550832:web:b764da4e6c16cbd183b8f5',
    messagingSenderId: '889846550832',
    projectId: 'dscvr-9d362',
    authDomain: 'dscvr-9d362.firebaseapp.com',
    storageBucket: 'dscvr-9d362.firebasestorage.app',
    measurementId: 'G-P5RQNH9NHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-IgpAMhrCftV6BdN3_LW2i3ZSxD8BP-E',
    appId: '1:889846550832:android:78466cde099de41183b8f5',
    messagingSenderId: '889846550832',
    projectId: 'dscvr-9d362',
    storageBucket: 'dscvr-9d362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc7PVSLfDtv8udFx_xkp8MiSrFEBuoxTk',
    appId: '1:889846550832:ios:56d9121c03953eaf83b8f5',
    messagingSenderId: '889846550832',
    projectId: 'dscvr-9d362',
    storageBucket: 'dscvr-9d362.firebasestorage.app',
    iosBundleId: 'com.example.dscvr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc7PVSLfDtv8udFx_xkp8MiSrFEBuoxTk',
    appId: '1:889846550832:ios:56d9121c03953eaf83b8f5',
    messagingSenderId: '889846550832',
    projectId: 'dscvr-9d362',
    storageBucket: 'dscvr-9d362.firebasestorage.app',
    iosBundleId: 'com.example.dscvr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNDuPlEGh1EMomSokJbz4n25IUfMAjfWk',
    appId: '1:889846550832:web:bee8e7cae6f9d4ae83b8f5',
    messagingSenderId: '889846550832',
    projectId: 'dscvr-9d362',
    authDomain: 'dscvr-9d362.firebaseapp.com',
    storageBucket: 'dscvr-9d362.firebasestorage.app',
    measurementId: 'G-49P9W3SXBG',
  );
}
